import * as React from 'react';
import {
  Button,
  FluentProvider,
  makeStyles,
  Theme,
  tokens,
  webLightTheme,
  type JSXElement,
} from '@fluentui/react-components';
import { SEMANTIC_STYLE_HOOKS } from '@fluentui/semantic-style-hooks-preview';
import { bundleIcon, CalendarMonthFilled, CalendarMonthRegular } from '@fluentui/react-icons';

type VisualRefreshTheme = Record<string, string>;

const visualRefreshTokens: Partial<Record<keyof VisualRefreshTheme, string>> = {
  ...tokens,
  'smtc-group-button-stroke-width': '1px',
  'smtc-group-button-neutral-background': '#fafafa',
  'smtc-group-button-neutral-background-hover': '#f0f0f0',
  'smtc-group-button-neutral-background-pressed': '#dbdbdb',
  'smtc-group-button-neutral-background-selected': '#fafafa',
  'smtc-group-button-neutral-background-hover-selected': '#f0f0f0',
  'smtc-group-button-neutral-background-pressed-selected': '#dbdbdb',
  'smtc-group-button-neutral-background-disabled': '#f0f0f0',
  'smtc-group-button-primary-background': '#03787c',
  'smtc-group-button-primary-background-hover': '#02494c',
  'smtc-group-button-primary-background-pressed': '#00393d',
  'smtc-group-button-primary-background-selected': '#03787c',
  'smtc-group-button-primary-background-hover-selected': '#02494c',
  'smtc-group-button-primary-background-pressed-selected': '#00393d',
  'smtc-group-button-primary-background-disabled': '#f0f0f0',
  'smtc-group-button-outline-background': 'transparent',
  'smtc-group-button-outline-background-hover': 'transparent',
  'smtc-group-button-outline-background-pressed': 'transparent',
  'smtc-group-button-outline-background-selected': 'transparent',
  'smtc-group-button-outline-background-hover-selected': 'transparent',
  'smtc-group-button-outline-background-pressed-selected': 'transparent',
  'smtc-group-button-outline-background-disabled': 'transparent',
  'smtc-group-button-subtle-background': 'transparent',
  'smtc-group-button-subtle-background-hover': '#f5f5f5',
  'smtc-group-button-subtle-background-pressed': '#e0e0e0',
  'smtc-group-button-subtle-background-selected': 'transparent',
  'smtc-group-button-subtle-background-hover-selected': '#f5f5f5',
  'smtc-group-button-subtle-background-pressed-selected': '#e0e0e0',
  'smtc-group-button-subtle-background-disabled': 'transparent',
  'smtc-group-button-transparent-background': 'transparent',
  'smtc-group-button-transparent-background-hover': 'transparent',
  'smtc-group-button-transparent-background-pressed': 'transparent',
  'smtc-group-button-transparent-background-selected': 'transparent',
  'smtc-group-button-transparent-background-hover-selected': 'transparent',
  'smtc-group-button-transparent-background-pressed-selected': 'transparent',
  'smtc-group-button-transparent-background-disabled': 'transparent',
  'smtc-group-button-neutral-stroke': '#d1d1d1',
  'smtc-group-button-neutral-stroke-hover': '#c7c7c7',
  'smtc-group-button-neutral-stroke-pressed': '#b3b3b3',
  'smtc-group-button-neutral-stroke-selected': '#d1d1d1',
  'smtc-group-button-neutral-stroke-hover-selected': '#c7c7c7',
  'smtc-group-button-neutral-stroke-pressed-selected': '#b3b3b3',
  'smtc-group-button-neutral-stroke-disabled': '#e0e0e0',
  'smtc-group-button-primary-stroke': 'transparent',
  'smtc-group-button-primary-stroke-hover': 'transparent',
  'smtc-group-button-primary-stroke-pressed': 'transparent',
  'smtc-group-button-primary-stroke-selected': 'transparent',
  'smtc-group-button-primary-stroke-hover-selected': 'transparent',
  'smtc-group-button-primary-stroke-pressed-selected': 'transparent',
  'smtc-group-button-primary-stroke-disabled': 'transparent',
  'smtc-group-button-outline-stroke': '#d1d1d1',
  'smtc-group-button-outline-stroke-hover': '#c7c7c7',
  'smtc-group-button-outline-stroke-pressed': '#b3b3b3',
  'smtc-group-button-outline-stroke-selected': '#d1d1d1',
  'smtc-group-button-outline-stroke-hover-selected': '#c7c7c7',
  'smtc-group-button-outline-stroke-pressed-selected': '#b3b3b3',
  'smtc-group-button-outline-stroke-disabled': '#e0e0e0',
  'smtc-group-button-subtle-stroke': 'transparent',
  'smtc-group-button-subtle-stroke-hover': 'transparent',
  'smtc-group-button-subtle-stroke-pressed': 'transparent',
  'smtc-group-button-subtle-stroke-selected': 'transparent',
  'smtc-group-button-subtle-stroke-hover-selected': 'transparent',
  'smtc-group-button-subtle-stroke-pressed-selected': 'transparent',
  'smtc-group-button-subtle-stroke-disabled': 'transparent',
  'smtc-group-button-transparent-stroke': 'transparent',
  'smtc-group-button-transparent-stroke-hover': 'transparent',
  'smtc-group-button-transparent-stroke-pressed': 'transparent',
  'smtc-group-button-transparent-stroke-selected': 'transparent',
  'smtc-group-button-transparent-stroke-hover-selected': 'transparent',
  'smtc-group-button-transparent-stroke-pressed-selected': 'transparent',
  'smtc-group-button-transparent-stroke-disabled': 'transparent',
  'smtc-group-button-small-padding-horizontal': '8px',
  'smtc-group-button-small-padding-top': '4px',
  'smtc-group-button-small-padding-bottom': '4px',
  'smtc-group-button-small-gap': '4px',
  'smtc-group-button-small-minwidth': '64px',
  'smtc-group-button-small-minheight': '28px',
  'smtc-group-button-medium-padding-horizontal': '12px',
  'smtc-group-button-medium-padding-top': '8px',
  'smtc-group-button-medium-padding-bottom': '8px',
  'smtc-group-button-medium-gap': '6px',
  'smtc-group-button-medium-minwidth': '96px',
  'smtc-group-button-medium-minheight': '36px',
  'smtc-group-button-large-padding-horizontal': '12px',
  'smtc-group-button-large-padding-top': '10px',
  'smtc-group-button-large-padding-bottom': '10px',
  'smtc-group-button-large-gap': '6px',
  'smtc-group-button-large-minwidth': '96px',
  'smtc-group-button-large-minheight': '40px',
  'smtc-group-button-small-corner': '12px',
  'smtc-group-button-small-corner-hover': '12px',
  'smtc-group-button-small-corner-pressed': '12px',
  'smtc-group-button-small-corner-selected': '12px',
  'smtc-group-button-small-corner-hover-selected': '12px',
  'smtc-group-button-small-corner-pressed-selected': '12px',
  'smtc-group-button-small-corner-disabled': '12px',
  'smtc-group-button-medium-corner': '12px',
  'smtc-group-button-medium-corner-hover': '12px',
  'smtc-group-button-medium-corner-pressed': '12px',
  'smtc-group-button-medium-corner-selected': '12px',
  'smtc-group-button-medium-corner-hover-selected': '12px',
  'smtc-group-button-medium-corner-pressed-selected': '12px',
  'smtc-group-button-medium-corner-disabled': '12px',
  'smtc-group-button-large-corner': '12px',
  'smtc-group-button-large-corner-hover': '12px',
  'smtc-group-button-large-corner-pressed': '12px',
  'smtc-group-button-large-corner-selected': '12px',
  'smtc-group-button-large-corner-hover-selected': '12px',
  'smtc-group-button-large-corner-pressed-selected': '12px',
  'smtc-group-button-large-corner-disabled': '12px',
  'smtc-group-button-outline-stroke-width': '1px',
  'smtc-group-button-outline-stroke-width-hover': '1px',
  'smtc-group-button-outline-stroke-width-pressed': '1px',
  'smtc-group-button-outline-stroke-width-selected': '3px',
  'smtc-group-button-neutral-shadow': '0 0 0 transparent',
  'smtc-group-button-neutral-shadow-disabled': '0 0 0 transparent',
  'smtc-group-button-neutral-shadow-selected': '0 0 0 transparent',
  'smtc-group-button-neutral-shadow-disabled-selected': '0 0 0 transparent',
  'smtc-group-button-primary-shadow': '0 0 0 transparent',
  'smtc-group-button-primary-shadow-disabled': '0 0 0 transparent',
  'smtc-group-button-primary-shadow-selected': '0 0 0 transparent',
  'smtc-group-button-primary-shadow-disabled-selected': '0 0 0 transparent',
  'smtc-group-button-small-icononly-padding': '1px',
  'smtc-group-button-medium-icononly-padding': '5px',
  'smtc-group-button-large-icononly-padding': '7px',
  'smtc-group-button-neutral-icon-foreground': '#616161',
  'smtc-group-button-neutral-icon-foreground-hover': '#424242',
  'smtc-group-button-neutral-icon-foreground-pressed': '#00595D',
  'smtc-group-button-neutral-icon-foreground-disabled': '#bdbdbd',
  'smtc-group-button-neutral-icon-foreground-selected': '#616161',
  'smtc-group-button-primary-icon-foreground': '#ffffff',
  'smtc-group-button-primary-icon-foreground-hover': '#ffffff',
  'smtc-group-button-primary-icon-foreground-pressed': '#ffffff',
  'smtc-group-button-primary-icon-foreground-disabled': '#bdbdbd',
  'smtc-group-button-primary-icon-foreground-selected': '#ffffff',
  'smtc-group-button-outline-icon-foreground': '#616161',
  'smtc-group-button-outline-icon-foreground-hover': '#424242',
  'smtc-group-button-outline-icon-foreground-pressed': '#00595D',
  'smtc-group-button-outline-icon-foreground-disabled': '#bdbdbd',
  'smtc-group-button-outline-icon-foreground-selected': '#616161',
  'smtc-group-button-subtle-icon-foreground': '#616161',
  'smtc-group-button-subtle-icon-foreground-hover': '#00686D',
  'smtc-group-button-subtle-icon-foreground-pressed': '#00595D',
  'smtc-group-button-subtle-icon-foreground-disabled': '#bdbdbd',
  'smtc-group-button-subtle-icon-foreground-selected': '#616161',
  'smtc-group-button-transparent-icon-foreground': '#616161',
  'smtc-group-button-transparent-icon-foreground-hover': '#00686D',
  'smtc-group-button-transparent-icon-foreground-pressed': '#00595D',
  'smtc-group-button-transparent-icon-foreground-disabled': '#bdbdbd',
  'smtc-group-button-transparent-icon-foreground-selected': '#616161',
  'smtc-group-button-small-icon-size': '20px',
  'smtc-group-button-medium-icon-size': '20px',
  'smtc-group-button-large-icon-size': '24px',
  'smtc-group-button-divider-stroke-width': '1px',
  'smtc-group-button-divider-margin-vertical': '0px',
  'smtc-group-button-neutral-divider-foreground': '#d1d1d1',
  'smtc-group-button-primary-divider-foreground': '#ffffff',
  'smtc-group-button-outline-divider-foreground': '#d1d1d1',
  'smtc-group-button-subtle-divider-foreground': 'transparent',
  'smtc-group-button-transparent-divider-foreground': 'transparent',
  'smtc-group-button-neutral-chevron-foreground': '#616161',
  'smtc-group-button-neutral-chevron-foreground-hover': '#424242',
  'smtc-group-button-neutral-chevron-foreground-pressed': '#00595D',
  'smtc-group-button-neutral-chevron-foreground-selected': '#616161',
  'smtc-group-button-neutral-chevron-foreground-disabled': '#bdbdbd',
  'smtc-group-button-primary-chevron-foreground': '#ffffff',
  'smtc-group-button-primary-chevron-foreground-hover': '#ffffff',
  'smtc-group-button-primary-chevron-foreground-pressed': '#ffffff',
  'smtc-group-button-primary-chevron-foreground-selected': '#ffffff',
  'smtc-group-button-primary-chevron-foreground-disabled': '#bdbdbd',
  'smtc-group-button-outline-chevron-foreground': '#616161',
  'smtc-group-button-outline-chevron-foreground-hover': '#424242',
  'smtc-group-button-outline-chevron-foreground-pressed': '#00595D',
  'smtc-group-button-outline-chevron-foreground-selected': '#616161',
  'smtc-group-button-outline-chevron-foreground-disabled': '#bdbdbd',
  'smtc-group-button-subtle-chevron-foreground': '#616161',
  'smtc-group-button-subtle-chevron-foreground-hover': '#00686D',
  'smtc-group-button-subtle-chevron-foreground-pressed': '#00595D',
  'smtc-group-button-subtle-chevron-foreground-selected': '#616161',
  'smtc-group-button-subtle-chevron-foreground-disabled': '#bdbdbd',
  'smtc-group-button-transparent-chevron-foreground': '#616161',
  'smtc-group-button-transparent-chevron-foreground-hover': '#00686D',
  'smtc-group-button-transparent-chevron-foreground-pressed': '#00595D',
  'smtc-group-button-transparent-chevron-foreground-selected': '#616161',
  'smtc-group-button-transparent-chevron-foreground-disabled': '#bdbdbd',
  'smtc-group-button-small-chevron-size': '20px',
  'smtc-group-button-medium-chevron-size': '20px',
  'smtc-group-button-large-chevron-size': '24px',
  'smtc-group-button-text-fontfamily':
    "'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
  'smtc-group-button-neutral-text-foreground': '#616161',
  'smtc-group-button-neutral-text-hover': '#424242',
  'smtc-group-button-neutral-text-foreground-pressed': '#424242',
  'smtc-group-button-neutral-text-foreground-disabled': '#bdbdbd',
  'smtc-group-button-neutral-text-foreground-selected': '#616161',
  'smtc-group-button-primary-text-foreground': '#ffffff',
  'smtc-group-button-primary-text-foreground-hover': '#ffffff',
  'smtc-group-button-primary-text-foreground-pressed': '#ffffff',
  'smtc-group-button-primary-text-foreground-disabled': '#bdbdbd',
  'smtc-group-button-primary-text-foreground-selected': '#ffffff',
  'smtc-group-button-outline-text-foreground': '#616161',
  'smtc-group-button-outline-text-foreground-hover': '#424242',
  'smtc-group-button-outline-text-foreground-pressed': '#424242',
  'smtc-group-button-outline-text-foreground-disabled': '#bdbdbd',
  'smtc-group-button-outline-text-foreground-selected': '#616161',
  'smtc-group-button-subtle-text-foreground': '#616161',
  'smtc-group-button-subtle-text-foreground-hover': '#424242',
  'smtc-group-button-subtle-text-foreground-pressed': '#424242',
  'smtc-group-button-subtle-text-foreground-disabled': '#bdbdbd',
  'smtc-group-button-subtle-text-foreground-selected': '#616161',
  'smtc-group-button-transparent-text-foreground': '#616161',
  'smtc-group-button-transparent-text-foreground-hover': '#00686D',
  'smtc-group-button-transparent-text-foreground-pressed': '#00595D',
  'smtc-group-button-transparent-text-foreground-disabled': '#bdbdbd',
  'smtc-group-button-transparent-text-foreground-selected': '#616161',
  'smtc-group-button-small-text--padding-horizontal': '8px',
  'smtc-group-button-small-text-fontsize': '12px',
  'smtc-group-button-small-text-lineheight': '16px',
  'smtc-group-button-small-text-fontweight': '600',
  'smtc-group-button-medium-text-padding-horizontal': '12px',
  'smtc-group-button-medium-text-fontsize': '14px',
  'smtc-group-button-medium-text-lineheight': '20px',
  'smtc-group-button-medium-text-fontweight': '600',
  'smtc-group-button-large-text--padding-horizontal': '12px',
  'smtc-group-button-large-text-fontsize': '14px',
  'smtc-group-button-large-text-lineheight': '20px',
  'smtc-group-button-large-text-fontweight': '600',
  'smtc-group-button-small-text-fontweight-selected': '600',
  'smtc-group-button-medium-text-fontweight-selected': '600',
  'smtc-group-button-large-text-fontweight-selected': '600',
  'smtc-group-button-neutral-text-secondary-foreground': '#424242',
  'smtc-group-button-neutral-text-secondary-foreground-hover': '#242424',
  'smtc-group-button-neutral-text-secondary-foreground-pressed': '#242424',
  'smtc-group-button-neutral-text-secondary-foreground-disabled': '#bdbdbd',
  'smtc-group-button-primary-text-secondary-foreground': '#ffffff',
  'smtc-group-button-primary-text-secondary-foreground-hover': '#ffffff',
  'smtc-group-button-primary-text-secondary-foreground-pressed': '#ffffff',
  'smtc-group-button-primary-text-secondary-foreground-disabled': '#bdbdbd',
  'smtc-group-button-outline-text-secondary-foreground': '#424242',
  'smtc-group-button-outline-text-secondary-foreground-hover': '#242424',
  'smtc-group-button-outline-text-secondary-foreground-pressed': '#242424',
  'smtc-group-button-outline-text-secondary-foreground-disabled': '#bdbdbd',
  'smtc-group-button-subtle-text-secondary-foreground': '#424242',
  'smtc-group-button-subtle-text-secondary-foreground-hover': '#242424',
  'smtc-group-button-subtle-text-secondary-foreground-pressed': '#242424',
  'smtc-group-button-subtle-text-secondary-foreground-disabled': '#bdbdbd',
  'smtc-group-button-transparent-text-secondary-foreground': '#424242',
  'smtc-group-button-transparent-text-secondary-foreground-hover': '#242424',
  'smtc-group-button-transparent-text-secondary-foreground-pressed': '#242424',
  'smtc-group-button-transparent-text-secondary-foreground-disabled': '#bdbdbd',
  'smtc-group-button-small-text-secondary-fontsize': '12px',
  'smtc-group-button-small-text-secondary-lineheight': '100%',
  'smtc-group-button-small-text-secondary-fontweight': '400',
  'smtc-group-button-medium-text-secondary-fontsize': '12px',
  'smtc-group-button-medium-text-secondary-lineheight': '100%',
  'smtc-group-button-medium-text-secondary-fontweight': '400',
  'smtc-group-button-large-text-secondary-fontsize': '14px',
  'smtc-group-button-large-text-secondary-lineheight': '100%',
  'smtc-group-button-large-text-secondary-fontweight': '400',
};

const CalendarMonth = bundleIcon(CalendarMonthFilled, CalendarMonthRegular);

const useStyles = makeStyles({
  wrapper: {
    columnGap: '15px',
    display: 'flex',
  },
});

const visualRefreshTheme = { ...webLightTheme, ...visualRefreshTokens };

export const ButtonVisualRefresh = (): JSXElement => {
  const styles = useStyles();
  return (
    <FluentProvider theme={visualRefreshTheme as Partial<Theme>} customStyleHooks_unstable={SEMANTIC_STYLE_HOOKS}>
      <div className={styles.wrapper}>
        <Button icon={<CalendarMonthRegular />}>Default</Button>
        <Button appearance="primary" icon={<CalendarMonthRegular />}>
          Primary
        </Button>
        <Button appearance="outline" icon={<CalendarMonth />}>
          Outline
        </Button>
        <Button appearance="subtle" icon={<CalendarMonth />}>
          Subtle
        </Button>
        <Button appearance="transparent" icon={<CalendarMonth />}>
          Transparent
        </Button>
      </div>
    </FluentProvider>
  );
};

ButtonVisualRefresh.parameters = {
  docs: {
    description: {
      story: 'Compare Button variants across interaction states with and without the visual refresh theme.',
    },
  },
};
